name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to DigitalOcean via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e  # Exit on error
            
            # Set working directory
            PROJECT_DIR="/home/${{ secrets.DROPLET_USER }}/development/www/blog-starter-kit"
            
            # Ensure project directory exists
            mkdir -p $PROJECT_DIR
            cd $PROJECT_DIR
            
            # Ensure Git is installed
            if ! command -v git &> /dev/null; then
              echo "Installing Git..."
              apt update && apt install -y git
            fi
            
            # Ensure Node.js and npm are installed
            if ! command -v node &> /dev/null; then
              echo "Installing Node.js..."
              curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
              apt install -y nodejs
            fi
            
            # Ensure PM2 is installed
            if ! command -v pm2 &> /dev/null; then
              echo "Installing PM2..."
              npm install -g pm2
            fi

            # Ensure the repository exists
            if [ ! -d ".git" ]; then
              echo "Repository not found, cloning..."
              git clone git@github.com:NiallKahlout/blog-starter-kit.git .
            fi
            
            # Pull latest changes
            git fetch origin main
            git reset --hard origin/main

            # Install dependencies
            npm install --legacy-peer-deps

            # Build project
            npm run build

            # Start or restart PM2 process
            pm2 start npm --name blog -- run start || pm2 restart blog
            pm2 save
