name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}      # e.g., your_server_ip
          username: ${{ secrets.SERVER_USER }}    # e.g., your_username
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/development/www/blog-starter-kit
            git pull origin main
            npm install
            npm run build
            pm2 restart all
